// ─────────────────────────────────────────────────────────────────────────────
// AI feature types
//
// Currently used by AISummaryCard for algorithmic summaries derived directly
// from idea data.  When an AI provider key is configured
// (OPENAI_API_KEY / ANTHROPIC_API_KEY) the same structure is returned by the
// AI — keeping the UI layer provider-agnostic.
// ─────────────────────────────────────────────────────────────────────────────

export interface FlowTheme {
  theme: string
  count: number
  /** Representative idea titles that contain this theme */
  examples?: string[]
  sentiment?: 'positive' | 'neutral' | 'concern'
}

export interface FlowSummary {
  generatedAt: string
  roundId: string | null
  roundName: string | null
  totalIdeas: number
  participationRate: number
  participantCount: number
  memberCount: number
  themes: FlowTheme[]
  topIdeas: { title: string; likes: number; description?: string }[]
  keyInsights: string[]
  actionItems: string[]
  engagementLevel: 'strong' | 'good' | 'early' | 'none'
  /** true when generated by an AI provider; false for algorithmic fallback */
  aiPowered: boolean
}

// ── Future integration hooks ──────────────────────────────────────────────────
// Not yet implemented — structure is here for clean extensibility.

export interface SlackDigestConfig {
  channelId: string
  frequency: 'daily' | 'weekly'
  includeTopIdeas: boolean
  includeParticipationRate: boolean
}

export interface TeamsDigestConfig {
  webhookUrl: string
  enabled: boolean
  frequency: 'daily' | 'weekly'
}

export interface AIProviderConfig {
  provider: 'openai' | 'anthropic' | 'none'
  modelId?: string
  /** Name of the environment variable that holds the key */
  apiKeyEnvVar?: string
}

export interface DuplicateDetectionResult {
  /** Pairs of idea IDs that appear to cover the same topic */
  possibleDuplicates: Array<{ ideaIds: [string, string]; similarity: number }>
}
