'use client'

/**
 * AIInsightsPanel — Pro-only, live AI summary card for a single IdeaFlow.
 *
 * Behaviour:
 *   - On mount (and on roundId change) it calls POST /api/ai/insights.
 *   - On a successful response it renders the model's headline, observations,
 *     recommendations, and themes.
 *   - On 403 it renders the Pro upgrade teaser (defence in depth — the page
 *     should already not render this component for non-Pro plans).
 *   - On 503 (AI not configured) it renders a clear "configure
 *     ANTHROPIC_API_KEY" hint to the admin.
 *   - On 502 / network failure it renders a transient-error retry button.
 *   - On 200 with `empty: true` it renders a friendly "not enough data" state.
 */

import { useEffect, useState } from 'react'

interface AIInsight {
  headline:        string
  observations:    string[]
  recommendations: string[]
  themes:          string[]
}

type ApiState =
  | { kind: 'loading' }
  | { kind: 'ok'; data: AIInsight }
  | { kind: 'empty' }
  | { kind: 'not-configured' }
  | { kind: 'not-entitled' }
  | { kind: 'transient'; message: string }

interface Props {
  roundId:  string
  roundName: string | null
}

export default function AIInsightsPanel({ roundId, roundName }: Props) {
  const [state, setState] = useState<ApiState>({ kind: 'loading' })

  useEffect(() => {
    let cancelled = false
    setState({ kind: 'loading' })

    fetch('/api/ai/insights', {
      method:  'POST',
      headers: { 'Content-Type': 'application/json' },
      body:    JSON.stringify({ roundId }),
    })
      .then(async res => {
        const data = await res.json().catch(() => ({} as Record<string, unknown>))
        if (cancelled) return

        if (res.status === 403) {
          setState({ kind: 'not-entitled' })
          return
        }
        if (res.status === 503 && data.aiConfigured === false) {
          setState({ kind: 'not-configured' })
          return
        }
        if (res.ok && (data as { empty?: boolean }).empty) {
          setState({ kind: 'empty' })
          return
        }
        if (res.ok && (data as Partial<AIInsight>).headline) {
          setState({
            kind: 'ok',
            data: {
              headline:        String((data as AIInsight).headline),
              observations:    (data as AIInsight).observations    ?? [],
              recommendations: (data as AIInsight).recommendations ?? [],
              themes:          (data as AIInsight).themes          ?? [],
            },
          })
          return
        }
        const message = typeof (data as { error?: string }).error === 'string'
          ? (data as { error: string }).error
          : 'AI service did not respond.'
        setState({ kind: 'transient', message })
      })
      .catch((err: unknown) => {
        if (cancelled) return
        setState({ kind: 'transient', message: err instanceof Error ? err.message : 'Network error' })
      })

    return () => { cancelled = true }
  }, [roundId])

  return (
    <section
      style={{
        marginTop:    '2rem',
        borderRadius: '1rem',
        border:       '1px solid rgba(26,107,191,0.09)',
        background:   '#ffffff',
        overflow:     'hidden',
      }}
    >
      {/* Header */}
      <div style={{
        padding:      '0.875rem 1.25rem',
        borderBottom: '1px solid rgba(0,0,0,0.05)',
        display:      'flex',
        alignItems:   'center',
        gap:          '0.625rem',
      }}>
        <span aria-hidden style={{ fontSize: '1rem' }}>✨</span>
        <div style={{ flex: 1, minWidth: 0 }}>
          <p style={{ fontSize: '0.875rem', fontWeight: 700, color: '#0d1f35' }}>
            {roundName ? `${roundName} — AI Insights` : 'AI Insights'}
          </p>
          <p style={{ fontSize: '0.72rem', color: '#8b96a8' }}>
            Generated by Claude from this IdeaFlow&apos;s ideas
          </p>
        </div>
        <span style={{
          flexShrink:    0,
          fontSize:      '0.6rem',
          fontWeight:    700,
          letterSpacing: '0.08em',
          textTransform: 'uppercase',
          background:    'linear-gradient(135deg, rgba(249,115,22,0.12), rgba(234,88,12,0.06))',
          color:         '#c2540a',
          padding:       '0.25rem 0.625rem',
          borderRadius:  '999px',
          border:        '1px solid rgba(249,115,22,0.2)',
        }}>
          ✦ Pro
        </span>
      </div>

      {/* Body */}
      <div style={{ padding: '1.25rem 1.375rem' }}>
        {state.kind === 'loading' && (
          <p style={{ fontSize: '0.85rem', color: '#8b96a8' }}>
            Analyzing your ideas…
          </p>
        )}

        {state.kind === 'empty' && (
          <p style={{ fontSize: '0.85rem', color: '#8b96a8' }}>
            Not enough ideas in this flow yet for an AI summary.
          </p>
        )}

        {state.kind === 'not-entitled' && (
          <p style={{ fontSize: '0.85rem', color: '#8b96a8' }}>
            AI insights are part of the Pro plan.{' '}
            <a href="/settings" style={{ color: '#c2540a', fontWeight: 600, textDecoration: 'none' }}>
              Upgrade →
            </a>
          </p>
        )}

        {state.kind === 'not-configured' && (
          <div style={{
            fontSize: '0.825rem',
            color: '#475569',
            lineHeight: 1.6,
          }}>
            <p style={{ marginBottom: '0.4rem', fontWeight: 600 }}>
              AI is not configured on this deployment.
            </p>
            <p style={{ fontSize: '0.775rem', color: '#94a3b8' }}>
              Set the <code style={{ background: 'rgba(0,0,0,0.05)', padding: '0.05rem 0.3rem', borderRadius: '0.25rem' }}>ANTHROPIC_API_KEY</code> environment variable in
              your hosting provider to enable real AI insights. The rest of
              the analytics dashboard continues to work without it.
            </p>
          </div>
        )}

        {state.kind === 'transient' && (
          <div style={{ fontSize: '0.825rem', color: '#dc2626' }}>
            {state.message}
          </div>
        )}

        {state.kind === 'ok' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            {/* Headline */}
            <p style={{ fontSize: '0.95rem', lineHeight: 1.55, color: '#0d1f35', fontWeight: 500 }}>
              {state.data.headline}
            </p>

            {/* Themes */}
            {state.data.themes.length > 0 && (
              <div>
                <p style={SECTION_LABEL}>Themes</p>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.375rem' }}>
                  {state.data.themes.map(theme => (
                    <span key={theme} style={{
                      fontSize:     '0.75rem',
                      fontWeight:   500,
                      background:   'rgba(26,107,191,0.06)',
                      color:        '#1a6bbf',
                      padding:      '0.2rem 0.6rem',
                      borderRadius: '999px',
                      border:       '1px solid rgba(26,107,191,0.12)',
                    }}>
                      {theme}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Observations */}
            {state.data.observations.length > 0 && (
              <div>
                <p style={SECTION_LABEL}>Observations</p>
                <ul style={LIST_RESET}>
                  {state.data.observations.map((o, i) => (
                    <li key={i} style={LIST_ITEM}>
                      <span aria-hidden style={DOT_GREEN} />
                      <span style={{ flex: 1 }}>{o}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Recommendations */}
            {state.data.recommendations.length > 0 && (
              <div>
                <p style={SECTION_LABEL}>Recommendations</p>
                <ul style={LIST_RESET}>
                  {state.data.recommendations.map((r, i) => (
                    <li key={i} style={LIST_ITEM}>
                      <span aria-hidden style={DOT_ORANGE} />
                      <span style={{ flex: 1 }}>{r}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}
      </div>
    </section>
  )
}

// ── Style tokens ────────────────────────────────────────────────────────────

const SECTION_LABEL: React.CSSProperties = {
  fontSize:      '0.66rem',
  fontWeight:    700,
  letterSpacing: '0.10em',
  textTransform: 'uppercase',
  color:         '#94a3b8',
  marginBottom:  '0.5rem',
}

const LIST_RESET: React.CSSProperties = {
  listStyle: 'none',
  padding:   0,
  margin:    0,
  display:   'flex',
  flexDirection: 'column',
  gap:       '0.4rem',
}

const LIST_ITEM: React.CSSProperties = {
  display:    'flex',
  alignItems: 'flex-start',
  gap:        '0.5rem',
  fontSize:   '0.85rem',
  color:      '#0d1f35',
  lineHeight: 1.55,
}

const DOT_GREEN: React.CSSProperties = {
  marginTop:     '0.55rem',
  width:         '5px',
  height:        '5px',
  borderRadius:  '50%',
  background:    '#10b981',
  flexShrink:    0,
}

const DOT_ORANGE: React.CSSProperties = {
  marginTop:     '0.55rem',
  width:         '5px',
  height:        '5px',
  borderRadius:  '50%',
  background:    '#f97316',
  flexShrink:    0,
}
